
[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true
